class GameContents {
  String name;
  String index;

  GameContents({
    required this.name,
    required this.index,
  });
}

final List<GameContents> choi = [
  GameContents(name: 'ㄷ ㅁ', index: '1'),
  GameContents(name: 'ㅁ ㄹ', index: '2'),
  GameContents(name: 'ㄱ ㄷ', index: '3'),
  GameContents(name: 'ㅈ ㄱ', index: '4'),
  GameContents(name: 'ㄴ ㅇ', index: '5'),
  GameContents(name: 'ㄱ ㄹ', index: '6'),
  GameContents(name: 'ㅁ ㄱ', index: '7'),
  GameContents(name: 'ㄱ ㅅ', index: '8'),
  GameContents(name: 'ㄷ ㄹ', index: '9'),
  GameContents(name: 'ㅎ ㅎ', index: '10'),
  GameContents(name: 'ㄱ ㅇ', index: '11'),
  GameContents(name: 'ㅅ ㄷ', index: '12'),
  GameContents(name: 'ㅇ ㅈ', index: '13'),
  GameContents(name: 'ㅂ ㅇ', index: '14'),
  GameContents(name: 'ㄴ ㄱ', index: '15'),
  GameContents(name: 'ㄱ ㅂ', index: '16'),
  GameContents(name: 'ㅂ ㅈ', index: '17'),
  GameContents(name: 'ㅇ ㄱ', index: '18'),
  GameContents(name: 'ㅅ ㄱ', index: '19'),
  GameContents(name: 'ㄴ ㄹ', index: '20'),
  GameContents(name: 'ㄱ ㅊ', index: '21'),
  GameContents(name: 'ㅂ ㅁ', index: '22'),
  GameContents(name: 'ㄴ ㅂ', index: '23'),
  GameContents(name: 'ㅇ ㅁ', index: '24'),
  GameContents(name: 'ㄷ ㄱ', index: '25'),
  GameContents(name: 'ㄱ ㄱ', index: '26'),
  GameContents(name: 'ㅅ ㅁ', index: '27'),
  GameContents(name: 'ㅁ ㅁ', index: '28'),
  GameContents(name: 'ㄷ ㅂ', index: '29'),
  GameContents(name: 'ㅂ ㅈ', index: '30'),
  GameContents(name: 'ㄱ ㅈ', index: '31'),
  GameContents(name: 'ㅁ ㅇ', index: '32'),
  GameContents(name: 'ㅅ ㅈ', index: '33'),
  GameContents(name: 'ㅍ ㄹ', index: '34'),
  GameContents(name: 'ㅁ ㅂ', index: '35'),
  GameContents(name: 'ㄴ ㅁ', index: '36'),
  GameContents(name: 'ㅎ ㅇ', index: '37'),
  GameContents(name: 'ㄷ ㅇ', index: '38'),
  GameContents(name: 'ㅂ ㅅ', index: '39'),
  GameContents(name: 'ㅅ ㄹ', index: '40'),
  GameContents(name: 'ㅇ ㅅ', index: '41'),
  GameContents(name: 'ㅂ ㄱ', index: '42'),
  GameContents(name: 'ㄷ ㅈ', index: '43'),
  GameContents(name: 'ㅈ ㅅ', index: '44'),
  GameContents(name: 'ㅅ ㅇ', index: '45'),
  GameContents(name: 'ㅇ ㄹ', index: '46'),
  GameContents(name: 'ㅂ ㅎ', index: '47'),
  GameContents(name: 'ㅎ ㅅ', index: '48'),
  GameContents(name: 'ㅇ ㅂ', index: '49'),
  GameContents(name: 'ㅂ ㅂ', index: '50'),
];

final List<GameContents> person = [
  GameContents(name: 'assets/person/류승범.WEBP', index: '1'),
  GameContents(name: 'assets/person/강동원.WEBP', index: '2'),
  GameContents(name: 'assets/person/남도일.WEBP', index: '3'),
  GameContents(name: 'assets/person/강백호.JPG', index: '4'),
  GameContents(name: 'assets/person/공유.WEBP', index: '5'),
  GameContents(name: 'assets/person/미나.WEBP', index: '6'),
  GameContents(name: 'assets/person/김태희.WEBP', index: '7'),
  GameContents(name: 'assets/person/송혜교.WEBP', index: '8'),
  GameContents(name: 'assets/person/박재범.WEBP', index: '9'),
  GameContents(name: 'assets/person/수지.JPG', index: '10'),
  GameContents(name: 'assets/person/김동현.WEBP', index: '11'),
  GameContents(name: 'assets/person/링컨.WEBP', index: '12'),
  GameContents(name: 'assets/person/유관순.WEBP', index: '13'),
  GameContents(name: 'assets/person/Deadpool.JPG', index: '14'),
  GameContents(name: 'assets/person/로버트.WEBP', index: '15'),
  GameContents(name: 'assets/person/민경훈.jpeg', index: '16'),
  GameContents(name: 'assets/person/보노보노.WEBP', index: '17'),
  GameContents(name: 'assets/person/스칼렛요한슨.JPG', index: '18'),
  GameContents(name: 'assets/person/올라프.JPG', index: '19'),
  GameContents(name: 'assets/person/이승우.JPG', index: '20'),
  GameContents(name: 'assets/person/안재홍.WEBP', index: '21'),
  GameContents(name: 'assets/person/손흥민.JPG', index: '22'),
  GameContents(name: 'assets/person/강하늘.WEBP', index: '23'),
  GameContents(name: 'assets/person/거미.WEBP', index: '24'),
  GameContents(name: 'assets/person/고윤정.WEBP', index: '25'),
  GameContents(name: 'assets/person/미달이.WEBP', index: '26'),
  GameContents(name: 'assets/person/뿡뿡이.WEBP', index: '27'),
  GameContents(name: 'assets/person/어피치.WEBP', index: '28'),
  GameContents(name: 'assets/person/해린.JPG', index: '29'),
  GameContents(name: 'assets/person/Justin Bieber.png', index: '30'),
  GameContents(name: 'assets/person/조정석.WEBP', index: '31'),
  GameContents(name: 'assets/person/조유리.WEBP', index: '32'),
  GameContents(name: 'assets/person/정 동원.jpeg', index: '33'),
  GameContents(name: 'assets/person/무민.JPG', index: '34'),
  GameContents(name: 'assets/person/샘스미스.WEBP', index: '35'),
  GameContents(name: 'assets/person/현주엽.WEBP', index: '36'),
  GameContents(name: 'assets/person/전여빈.WEBP', index: '37'),
  GameContents(name: 'assets/person/김연경.jpeg', index: '38'),
  GameContents(name: 'assets/person/타노스.WEBP', index: '39'),
  GameContents(name: 'assets/person/김소연.WEBP', index: '40'),
  GameContents(name: 'assets/person/조승우.JPG', index: '41'),
  GameContents(name: 'assets/person/안나.JPG', index: '42'),
  GameContents(name: 'assets/person/포돌이.WEBP', index: '43'),
  GameContents(name: 'assets/person/이문세.WEBP', index: '44'),
  GameContents(name: 'assets/person/문상훈.WEBP', index: '45'),
  GameContents(name: 'assets/person/지성.WEBP', index: '46'),
  GameContents(name: 'assets/person/이경영.WEBP', index: '47'),
  GameContents(name: 'assets/person/피오나.WEBP', index: '48'),
  GameContents(name: 'assets/person/winter.jpeg', index: '49'),
  GameContents(name: 'assets/person/고아성.WEBP', index: '50'),
];
<<<<<<< HEAD

final List<GameContents> person2 = [
  GameContents(name: 'assets/person/김동현.WEBP', index: '1'),
  GameContents(name: 'assets/person/링컨.WEBP', index: '2'),
  GameContents(name: 'assets/person/유관순.WEBP', index: '3'),
  GameContents(name: 'assets/person/데드풀.JPG', index: '4'),
  GameContents(name: 'assets/person/로버트.WEBP', index: '5'),
  GameContents(name: 'assets/person/민경훈.jpeg', index: '6'),
  GameContents(name: 'assets/person/보노보노.WEBP', index: '7'),
  GameContents(name: 'assets/person/스칼렛요한슨.JPG', index: '8'),
  GameContents(name: 'assets/person/올라프.JPG', index: '9'),
  GameContents(name: 'assets/person/이승우.JPG', index: '10'),
];

final List<GameContents> person3 = [
  GameContents(name: 'assets/person/안재홍.WEBP', index: '1'),
  GameContents(name: 'assets/person/손흥민.JPG', index: '2'),
  GameContents(name: 'assets/person/강하늘.WEBP', index: '3'),
  GameContents(name: 'assets/person/거미.WEBP', index: '4'),
  GameContents(name: 'assets/person/고윤정.WEBP', index: '5'),
  GameContents(name: 'assets/person/미달이.WEBP', index: '6'),
  GameContents(name: 'assets/person/뿡뿡이.WEBP', index: '7'),
  GameContents(name: 'assets/person/어피치.WEBP', index: '8'),
  GameContents(name: 'assets/person/해린.JPG', index: '9'),
  GameContents(name: 'assets/person/저스틴비버.png', index: '10'),
];

final List<GameContents> person4 = [
  GameContents(name: 'assets/person/조정석.WEBP', index: '1'),
  GameContents(name: 'assets/person/조유리.WEBP', index: '2'),
  GameContents(name: 'assets/person/정 동원.jpeg', index: '3'),
  GameContents(name: 'assets/person/무민.JPG', index: '4'),
  GameContents(name: 'assets/person/샘스미스.WEBP', index: '5'),
  GameContents(name: 'assets/person/현주엽.WEBP', index: '6'),
  GameContents(name: 'assets/person/전여빈.WEBP', index: '7'),
  GameContents(name: 'assets/person/김연경.jpeg', index: '8'),
  GameContents(name: 'assets/person/타노스.WEBP', index: '9'),
  GameContents(name: 'assets/person/김소연.WEBP', index: '10'),
];

final List<GameContents> person5 = [
  GameContents(name: 'assets/person/조승우.JPG', index: '1'),
  GameContents(name: 'assets/person/안나.JPG', index: '2'),
  GameContents(name: 'assets/person/포돌이.WEBP', index: '3'),
  GameContents(name: 'assets/person/이문세.WEBP', index: '4'),
  GameContents(name: 'assets/person/문상훈.WEBP', index: '5'),
  GameContents(name: 'assets/person/지성.WEBP', index: '6'),
  GameContents(name: 'assets/person/이경영.WEBP', index: '7'),
  GameContents(name: 'assets/person/피오나.WEBP', index: '8'),
  GameContents(name: 'assets/person/윈터.jpeg', index: '9'),
  GameContents(name: 'assets/person/고아성.WEBP', index: '10'),
];

final List<GameContents> four1 = [
=======
final List<GameContents> four = [
>>>>>>> cb7b4342a1d6bddb7c50bee95fecd85c80ef4dd2
  GameContents(name: '이구_ _', index: '1'),
  GameContents(name: '동문_ _', index: '2'),
  GameContents(name: '드라_ _', index: '3'),
  GameContents(name: '게르_ _', index: '4'),
  GameContents(name: '안전_ _', index: '5'),
  GameContents(name: '고슴_ _', index: '6'),
  GameContents(name: '오토_ _', index: '7'),
  GameContents(name: '파인_ _', index: '8'),
  GameContents(name: '레이_ _', index: '9'),
  GameContents(name: '예방_ _', index: '10'),
  GameContents(name: '고객_ _', index: '11'),
  GameContents(name: '샌드_ _', index: '12'),
  GameContents(name: '유통_ _', index: '13'),
  GameContents(name: '호랑_ _', index: '14'),
  GameContents(name: '술래_ _', index: '15'),
  GameContents(name: '프리_ _', index: '16'),
  GameContents(name: '분리_ _', index: '17'),
  GameContents(name: '초코_ _', index: '18'),
  GameContents(name: '해바_ _', index: '19'),
  GameContents(name: '코스_ _', index: '20'),
  GameContents(name: '카놀_ _', index: '21'),
  GameContents(name: '어린_ _', index: '22'),
  GameContents(name: '일기_ _', index: '23'),
  GameContents(name: '백설_ _', index: '24'),
  GameContents(name: '헤드_ _', index: '25'),
  GameContents(name: '보사_ _', index: '26'),
  GameContents(name: '폼클_ _', index: '27'),
  GameContents(name: '오랑_ _', index: '28'),
  GameContents(name: '나무_ _', index: '29'),
  GameContents(name: '차돌_ _', index: '30'),
  GameContents(name: '치즈_ _', index: '31'),
  GameContents(name: '다이_ _', index: '32'),
  GameContents(name: '김치_ _', index: '33'),
  GameContents(name: '자급_ _', index: '34'),
  GameContents(name: '다이_ _', index: '35'),
  GameContents(name: '다사_ _', index: '36'),
  GameContents(name: '이모_ _', index: '37'),
  GameContents(name: '장기_ _', index: '38'),
  GameContents(name: '인테_ _', index: '39'),
  GameContents(name: '감자_ _', index: '40'),
  GameContents(name: '직사_ _', index: '41'),
  GameContents(name: '계란_ _', index: '42'),
  GameContents(name: '피라_ _', index: '43'),
  GameContents(name: '와이_ _', index: '44'),
  GameContents(name: '무당_ _', index: '45'),
  GameContents(name: '페이_ _', index: '46'),
  GameContents(name: '아나_ _', index: '47'),
  GameContents(name: '개미_ _', index: '48'),
  GameContents(name: '코카_ _', index: '49'),
  GameContents(name: '오피_ _', index: '50'),
];
final List<GameContents> tele = [
  GameContents(name: '가', index: '1'),
  GameContents(name: '다', index: '2'),
  GameContents(name: '나', index: '3'),
  GameContents(name: '물', index: '4'),
  GameContents(name: '자', index: '5'),
  GameContents(name: '우', index: '6'),
  GameContents(name: '하', index: '7'),
  GameContents(name: '기', index: '8'),
  GameContents(name: '이', index: '9'),
  GameContents(name: '산', index: '10'),
  GameContents(name: '시', index: '11'),
  GameContents(name: '아', index: '12'),
  GameContents(name: '화', index: '13'),
  GameContents(name: '마', index: '14'),
  GameContents(name: '조', index: '15'),
  GameContents(name: '모', index: '16'),
  GameContents(name: '도', index: '17'),
  GameContents(name: '라', index: '18'),
  GameContents(name: '호', index: '19'),
  GameContents(name: '이', index: '20'),
  GameContents(name: '레', index: '21'),
  GameContents(name: '내', index: '22'),
  GameContents(name: '네', index: '23'),
  GameContents(name: '사', index: '24'),
  GameContents(name: '감', index: '25'),
  GameContents(name: '기', index: '26'),
  GameContents(name: '가', index: '27'),
  GameContents(name: '아', index: '28'),
  GameContents(name: '마', index: '29'),
  GameContents(name: '이', index: '30'),
  GameContents(name: '중', index: '31'),
  GameContents(name: '미', index: '32'),
  GameContents(name: '일', index: '33'),
  GameContents(name: '우', index: '34'),
  GameContents(name: '자', index: '35'),
  GameContents(name: '라', index: '36'),
  GameContents(name: '나', index: '37'),
  GameContents(name: '모', index: '38'),
  GameContents(name: '인', index: '39'),
  GameContents(name: '민', index: '40'),
  GameContents(name: '지', index: '41'),
  GameContents(name: '물', index: '42'),
  GameContents(name: '불', index: '43'),
  GameContents(name: '산', index: '44'),
  GameContents(name: '거', index: '45'),
  GameContents(name: '토', index: '46'),
  GameContents(name: '월', index: '47'),
  GameContents(name: '나', index: '48'),
  GameContents(name: '구', index: '49'),
  GameContents(name: '원', index: '50'),
];
