class GameContents {
  String name;
  String index;
  String answer;

  GameContents({
    required this.name,
    required this.index,
    this.answer = '',
  });
}

final List<GameContents> person = [
  GameContents(name: 'assets/person/류승범.WEBP', index: '1'),
  GameContents(name: 'assets/person/강동원.WEBP', index: '2'),
  GameContents(name: 'assets/person/남도일.jpeg', index: '3'),
  GameContents(name: 'assets/person/강백호.jpeg', index: '4'),
  GameContents(name: 'assets/person/공유.WEBP', index: '5'),
  GameContents(name: 'assets/person/미나.WEBP', index: '6'),
  GameContents(name: 'assets/person/김태희.jpeg', index: '7'),
  GameContents(name: 'assets/person/송혜교.WEBP', index: '8'),
  GameContents(name: 'assets/person/박재범.WEBP', index: '9'),
  GameContents(name: 'assets/person/수지.JPG', index: '10'),
  GameContents(name: 'assets/person/김동현.WEBP', index: '11'),
  GameContents(name: 'assets/person/링컨.WEBP', index: '12'),
  GameContents(name: 'assets/person/유관순.WEBP', index: '13'),
  GameContents(name: 'assets/person/데드풀.jpeg', index: '14'),
  GameContents(name: 'assets/person/로버트 다우니 주니어.jpeg', index: '15'),
  GameContents(name: 'assets/person/민경훈.jpeg', index: '16'),
  GameContents(name: 'assets/person/보노보노.WEBP', index: '17'),
  GameContents(name: 'assets/person/스칼렛요한슨.JPG', index: '18'),
  GameContents(name: 'assets/person/올라프.JPG', index: '19'),
  GameContents(name: 'assets/person/이승우.jpeg', index: '20'),
  GameContents(name: 'assets/person/안재홍.WEBP', index: '21'),
  GameContents(name: 'assets/person/손흥민.JPG', index: '22'),
  GameContents(name: 'assets/person/강하늘.WEBP', index: '23'),
  GameContents(name: 'assets/person/거미.WEBP', index: '24'),
  GameContents(name: 'assets/person/고윤정.WEBP', index: '25'),
  GameContents(name: 'assets/person/미달이.WEBP', index: '26'),
  GameContents(name: 'assets/person/뿡뿡이.WEBP', index: '27'),
  GameContents(name: 'assets/person/어피치.png', index: '28'),
  GameContents(name: 'assets/person/해린.JPG', index: '29'),
  GameContents(name: 'assets/person/저스틴 비버.png', index: '30'),
  GameContents(name: 'assets/person/조정석.WEBP', index: '31'),
  GameContents(name: 'assets/person/조유리.png', index: '32'),
  GameContents(name: 'assets/person/정동원.jpeg', index: '33'),
  GameContents(name: 'assets/person/무민.JPG', index: '34'),
  GameContents(name: 'assets/person/샘스미스.WEBP', index: '35'),
  GameContents(name: 'assets/person/현주엽.WEBP', index: '36'),
  GameContents(name: 'assets/person/전여빈.WEBP', index: '37'),
  GameContents(name: 'assets/person/김연경.JPG', index: '38'),
  GameContents(name: 'assets/person/타노스.WEBP', index: '39'),
  GameContents(name: 'assets/person/김소연.WEBP', index: '40'),
  GameContents(name: 'assets/person/조승우.JPG', index: '41'),
  GameContents(name: 'assets/person/안나.JPG', index: '42'),
  GameContents(name: 'assets/person/포돌이.WEBP', index: '43'),
  GameContents(name: 'assets/person/이문세.WEBP', index: '44'),
  GameContents(name: 'assets/person/문상훈.WEBP', index: '45'),
  GameContents(name: 'assets/person/지성.WEBP', index: '46'),
  GameContents(name: 'assets/person/이경영.WEBP', index: '47'),
  GameContents(name: 'assets/person/피오나.WEBP', index: '48'),
  GameContents(name: 'assets/person/윈터.jpeg', index: '49'),
  GameContents(name: 'assets/person/고아성.WEBP', index: '50'),
  GameContents(name: 'assets/person/김연자.jpeg', index: '51'),
  GameContents(name: 'assets/person/마동석.jpeg', index: '52'),
  GameContents(name: 'assets/person/임영웅.jpeg', index: '53'),
  GameContents(name: 'assets/person/장윤주.jpeg', index: '54'),
  GameContents(name: 'assets/person/차두리.jpeg', index: '55'),
  GameContents(name: 'assets/person/나영석.WEBP', index: '56'),
  GameContents(name: 'assets/person/노진구.JPG', index: '57'),
  GameContents(name: 'assets/person/유해진.WEBP', index: '58'),
  GameContents(name: 'assets/person/최우식.JPG', index: '59'),
  GameContents(name: 'assets/person/크러쉬.JPG', index: '60'),
  GameContents(name: 'assets/person/박명수.WEBP', index: '61'),
  GameContents(name: 'assets/person/봉준호.WEBP', index: '62'),
  GameContents(name: 'assets/person/일론 머스크.WEBP', index: '63'),
  GameContents(name: 'assets/person/안유진.JPG', index: '64'),
];

final List<GameContents> disco = [
  GameContents(name: '사랑', index: '1'),
  GameContents(name: '너', index: '2'),
  GameContents(name: '나', index: '3'),
  GameContents(name: '우리', index: '4'),
  GameContents(name: '봄', index: '5'),
  GameContents(name: '여름', index: '6'),
  GameContents(name: '가을', index: '7'),
  GameContents(name: '겨울', index: '8'),
  GameContents(name: '당신', index: '9'),
  GameContents(name: '미안', index: '10'),
  GameContents(name: '손', index: '11'),
  GameContents(name: '바다', index: '12'),
  GameContents(name: '하늘', index: '13'),
  GameContents(name: '엄마', index: '14'),
  GameContents(name: '이별', index: '15'),
  GameContents(name: '눈물', index: '16'),
  GameContents(name: '꽃', index: '17'),
  GameContents(name: '서로', index: '18'),
  GameContents(name: '인연', index: '19'),
  GameContents(name: '널', index: '20'),
  GameContents(name: '안녕', index: '21'),
  GameContents(name: '진심', index: '22'),
  GameContents(name: '마음', index: '23'),
  GameContents(name: 'Love', index: '24'),
  GameContents(name: 'You', index: '25'),
  GameContents(name: 'Baby', index: '26'),
  GameContents(name: '인사', index: '27'),
  GameContents(name: '눈', index: '28'),
  GameContents(name: '비', index: '29'),
  GameContents(name: '바람', index: '30'),
  GameContents(name: '생각', index: '31'),
  GameContents(name: '가슴', index: '32'),
  GameContents(name: '고백', index: '33'),
  GameContents(name: '우주', index: '34'),
  GameContents(name: '별', index: '35'),
  GameContents(name: 'star', index: '36'),
  GameContents(name: '나무', index: '37'),
  GameContents(name: '자유', index: '38'),
  GameContents(name: '미련', index: '39'),
  GameContents(name: '정말', index: '40'),
  GameContents(name: '행복', index: '41'),
  GameContents(name: '하루', index: '42'),
  GameContents(name: '거짓말', index: '43'),
  GameContents(name: '풍선', index: '44'),
  GameContents(name: 'bye', index: '45'),
  GameContents(name: 'my', index: '46'),
  GameContents(name: '오늘', index: '47'),
  GameContents(name: '어제', index: '48'),
  GameContents(name: '내일', index: '49'),
  GameContents(name: '친구', index: '50'),
  GameContents(name: '꿀 honey', index: '51'),
  GameContents(name: '꿈', index: '52'),
  GameContents(name: '밤', index: '53'),
  GameContents(name: '낮', index: '54'),
];

final List<GameContents> captain = [
  GameContents(name: '가장 유연할 것 같은 사람', answer: '다리찢기', index: '1'),
  GameContents(name: '가장 노래를 잘 부를 것 같은 사람', answer: '절대음감', index: '2'),
  GameContents(name: '대머리가 제일 잘 어울릴 것 같은 사람', answer: '이마 길이 재기', index: '3'),
  GameContents(name: '공부 제일 잘 할 것 같은 사람', answer: '구구단', index: '4'),
  GameContents(name: '가장 춤 잘 출 것 같은 사람', answer: '국민체조', index: '5'),
  GameContents(name: '가장 운동 잘 할 것 같은 사람', answer: '미정', index: '6'),
  GameContents(name: '수업 시간에 졸 것 같은 사람', answer: '눈싸움', index: '7'),
  GameContents(name: '고등학생 때 담 넘어봤을 것 같은 사람', answer: '멀리뛰기', index: '8'),
  GameContents(name: '정색 가장 잘할 것 같은 사람', answer: '웃음 참기 게임', index: '9'),
  GameContents(name: '가장 당당해 보이는 사람', answer: '당연하지 게임', index: '10'),
  GameContents(name: '거짓말 못할 것 같은 사람', answer: '미정', index: '11'),
  GameContents(name: '눈물 많을 것 같은 사람', answer: '눈물 빨리 흘리기', index: '12'),
  GameContents(name: '무인도에서 살아남을 수 있을 것 같은 사람', answer: '미정', index: '13'),
  GameContents(
      name: '과자를 가장 많이 먹을 것 같은 사람', answer: '과자 부스러기 보고 과자 맞추기', index: '14'),
  GameContents(name: '타자가 가장 빠를 것 같은 사람', answer: '미정', index: '15'),
  GameContents(name: '어릴 때 사고 많이 쳤을 것 같은 사람', answer: '미정', index: '16'),
  GameContents(name: '문자보다 전화를 더 좋아할 것 같은 사람', answer: '콜백 챌린지', index: '17'),
  GameContents(name: 'SNS 가장 많이 할 것 같은 사람', answer: '눈 감고 타자 치기', index: '18'),
  GameContents(name: '감수성이 가장 풍부할 것 같은 사람', answer: '이름으로 삼행시 짓기', index: '19'),
  GameContents(name: '다정한 말 못하는 사람', answer: '옆사람 칭찬해주기', index: '20'),
];

final List<GameContents> choi = [
  GameContents(name: 'ㄷ ㅁ', index: '1'),
  GameContents(name: 'ㅁ ㄹ', index: '2'),
  GameContents(name: 'ㄱ ㄷ', index: '3'),
  GameContents(name: 'ㅈ ㄱ', index: '4'),
  GameContents(name: 'ㄴ ㅇ', index: '5'),
  GameContents(name: 'ㄱ ㄹ', index: '6'),
  GameContents(name: 'ㅁ ㄱ', index: '7'),
  GameContents(name: 'ㄱ ㅅ', index: '8'),
  GameContents(name: 'ㄷ ㄹ', index: '9'),
  GameContents(name: 'ㅎ ㅎ', index: '10'),
  GameContents(name: 'ㄱ ㅇ', index: '11'),
  GameContents(name: 'ㅅ ㄷ', index: '12'),
  GameContents(name: 'ㅇ ㅈ', index: '13'),
  GameContents(name: 'ㅂ ㅇ', index: '14'),
  GameContents(name: 'ㄴ ㄱ', index: '15'),
  GameContents(name: 'ㄱ ㅂ', index: '16'),
  GameContents(name: 'ㅂ ㅈ', index: '17'),
  GameContents(name: 'ㅇ ㄱ', index: '18'),
  GameContents(name: 'ㅅ ㄱ', index: '19'),
  GameContents(name: 'ㄴ ㄹ', index: '20'),
  GameContents(name: 'ㄱ ㅊ', index: '21'),
  GameContents(name: 'ㅂ ㅁ', index: '22'),
  GameContents(name: 'ㄴ ㅂ', index: '23'),
  GameContents(name: 'ㅇ ㅁ', index: '24'),
  GameContents(name: 'ㄷ ㄱ', index: '25'),
  GameContents(name: 'ㄱ ㄱ', index: '26'),
  GameContents(name: 'ㅅ ㅁ', index: '27'),
  GameContents(name: 'ㅁ ㅁ', index: '28'),
  GameContents(name: 'ㄷ ㅂ', index: '29'),
  GameContents(name: 'ㅂ ㅈ', index: '30'),
  GameContents(name: 'ㄱ ㅈ', index: '31'),
  GameContents(name: 'ㅁ ㅇ', index: '32'),
  GameContents(name: 'ㅅ ㅈ', index: '33'),
  GameContents(name: 'ㅍ ㄹ', index: '34'),
  GameContents(name: 'ㅁ ㅂ', index: '35'),
  GameContents(name: 'ㄴ ㅁ', index: '36'),
  GameContents(name: 'ㅎ ㅇ', index: '37'),
  GameContents(name: 'ㄷ ㅇ', index: '38'),
  GameContents(name: 'ㅂ ㅅ', index: '39'),
  GameContents(name: 'ㅅ ㄹ', index: '40'),
  GameContents(name: 'ㅇ ㅅ', index: '41'),
  GameContents(name: 'ㅂ ㄱ', index: '42'),
  GameContents(name: 'ㄷ ㅈ', index: '43'),
  GameContents(name: 'ㅈ ㅅ', index: '44'),
  GameContents(name: 'ㅅ ㅇ', index: '45'),
  GameContents(name: 'ㅇ ㄹ', index: '46'),
  GameContents(name: 'ㅂ ㅎ', index: '47'),
  GameContents(name: 'ㅎ ㅅ', index: '48'),
  GameContents(name: 'ㅇ ㅂ', index: '49'),
  GameContents(name: 'ㅂ ㅂ', index: '50'),
];
final List<GameContents> four = [
  GameContents(name: '이구 _ _', index: '1'),
  GameContents(name: '동문 _ _', index: '2'),
  GameContents(name: '드라 _ _', index: '3'),
  GameContents(name: '게르 _ _', index: '4'),
  GameContents(name: '안전 _ _', index: '5'),
  GameContents(name: '고슴 _ _', index: '6'),
  GameContents(name: '오토 _ _', index: '7'),
  GameContents(name: '파인 _ _', index: '8'),
  GameContents(name: '레이 _ _', index: '9'),
  GameContents(name: '예방 _ _', index: '10'),
  GameContents(name: '고객 _ _', index: '11'),
  GameContents(name: '샌드 _ _', index: '12'),
  GameContents(name: '유통 _ _', index: '13'),
  GameContents(name: '호랑 _ _', index: '14'),
  GameContents(name: '술래 _ _', index: '15'),
  GameContents(name: '프리 _ _', index: '16'),
  GameContents(name: '분리 _ _', index: '17'),
  GameContents(name: '초코 _ _', index: '18'),
  GameContents(name: '해바 _ _', index: '19'),
  GameContents(name: '코스 _ _', index: '20'),
  GameContents(name: '카놀 _ _', index: '21'),
  GameContents(name: '어린 _ _', index: '22'),
  GameContents(name: '일기 _ _', index: '23'),
  GameContents(name: '백설 _ _', index: '24'),
  GameContents(name: '헤드 _ _', index: '25'),
  GameContents(name: '보사 _ _', index: '26'),
  GameContents(name: '폼클 _ _', index: '27'),
  GameContents(name: '오랑 _ _', index: '28'),
  GameContents(name: '나무 _ _', index: '29'),
  GameContents(name: '차돌 _ _', index: '30'),
  GameContents(name: '치즈 _ _', index: '31'),
  GameContents(name: '다이 _ _', index: '32'),
  GameContents(name: '김치 _ _', index: '33'),
  GameContents(name: '자급 _ _', index: '34'),
  GameContents(name: '다이 _ _', index: '35'),
  GameContents(name: '다사 _ _', index: '36'),
  GameContents(name: '이모 _ _', index: '37'),
  GameContents(name: '장기 _ _', index: '38'),
  GameContents(name: '인테 _ _', index: '39'),
  GameContents(name: '감자 _ _', index: '40'),
  GameContents(name: '직사 _ _', index: '41'),
  GameContents(name: '계란 _ _', index: '42'),
  GameContents(name: '피라 _ _', index: '43'),
  GameContents(name: '와이 _ _', index: '44'),
  GameContents(name: '무당 _ _', index: '45'),
  GameContents(name: '페이 _ _', index: '46'),
  GameContents(name: '아나 _ _', index: '47'),
  GameContents(name: '개미 _ _', index: '48'),
  GameContents(name: '코카 _ _', index: '49'),
  GameContents(name: '오피 _ _', index: '50'),
];

final List<GameContents> tele = [
  GameContents(name: '가', index: '1'),
  GameContents(name: '다', index: '2'),
  GameContents(name: '나', index: '3'),
  GameContents(name: '물', index: '4'),
  GameContents(name: '자', index: '5'),
  GameContents(name: '우', index: '6'),
  GameContents(name: '하', index: '7'),
  GameContents(name: '기', index: '8'),
  GameContents(name: '이', index: '9'),
  GameContents(name: '산', index: '10'),
  GameContents(name: '시', index: '11'),
  GameContents(name: '아', index: '12'),
  GameContents(name: '화', index: '13'),
  GameContents(name: '마', index: '14'),
  GameContents(name: '조', index: '15'),
  GameContents(name: '모', index: '16'),
  GameContents(name: '도', index: '17'),
  GameContents(name: '라', index: '18'),
  GameContents(name: '호', index: '19'),
  GameContents(name: '이', index: '20'),
  GameContents(name: '레', index: '21'),
  GameContents(name: '내', index: '22'),
  GameContents(name: '네', index: '23'),
  GameContents(name: '사', index: '24'),
  GameContents(name: '감', index: '25'),
  GameContents(name: '기', index: '26'),
  GameContents(name: '가', index: '27'),
  GameContents(name: '아', index: '28'),
  GameContents(name: '마', index: '29'),
  GameContents(name: '이', index: '30'),
  GameContents(name: '중', index: '31'),
  GameContents(name: '미', index: '32'),
  GameContents(name: '일', index: '33'),
  GameContents(name: '우', index: '34'),
  GameContents(name: '자', index: '35'),
  GameContents(name: '라', index: '36'),
  GameContents(name: '나', index: '37'),
  GameContents(name: '모', index: '38'),
  GameContents(name: '인', index: '39'),
  GameContents(name: '민', index: '40'),
  GameContents(name: '지', index: '41'),
  GameContents(name: '물', index: '42'),
  GameContents(name: '불', index: '43'),
  GameContents(name: '산', index: '44'),
  GameContents(name: '거', index: '45'),
  GameContents(name: '토', index: '46'),
  GameContents(name: '월', index: '47'),
  GameContents(name: '나', index: '48'),
  GameContents(name: '구', index: '49'),
  GameContents(name: '원', index: '50'),
];

final List<GameContents> telestration = [
  GameContents(name: '스컹크', index: '1'),
  GameContents(name: '쿼카', index: '2'),
  GameContents(name: '엑스레이', index: '3'),
  GameContents(name: '번지점프', index: '4'),
  GameContents(name: '통나무집', index: '5'),
  GameContents(name: '공중전화', index: '6'),
  GameContents(name: '해외직구', index: '7'),
  GameContents(name: '미키마우스', index: '8'),
  GameContents(name: '찰리채플린', index: '9'),
  GameContents(name: '수족관', index: '10'),
  GameContents(name: '에펠탑', index: '11'),
  GameContents(name: '개미핥기', index: '12'),
  GameContents(name: '에어로빅', index: '13'),
  GameContents(name: '필라테스', index: '14'),
  GameContents(name: '합창단', index: '15'),
  GameContents(name: '어부', index: '16'),
  GameContents(name: '허수아비', index: '17'),
  GameContents(name: '치과의사', index: '18'),
  GameContents(name: '암벽등반', index: '19'),
  GameContents(name: '개그맨', index: '20'),
  GameContents(name: '경찰서', index: '21'),
  GameContents(name: '판사', index: '22'),
  GameContents(name: '연필깎이', index: '23'),
  GameContents(name: '타코야끼', index: '24'),
  GameContents(name: '금붕어', index: '25'),
  GameContents(name: '구미호', index: '26'),
  GameContents(name: '제빵사', index: '27'),
  GameContents(name: '평양냉면', index: '28'),
  GameContents(name: '크루아상', index: '29'),
  GameContents(name: '물개', index: '30'),
  GameContents(name: '티라노사우루스', index: '31'),
  GameContents(name: '우주정거장', index: '32'),
  GameContents(name: '서예', index: '33'),
  GameContents(name: '주먹도끼', index: '34'),
  GameContents(name: '빗살무늬토기', index: '35'),
  GameContents(name: '면접', index: '36'),
  GameContents(name: '야근', index: '37'),
  GameContents(name: '삼계탕', index: '38'),
  GameContents(name: '이순신장군', index: '39'),
  GameContents(name: '감자탕', index: '40'),
  GameContents(name: '낙동강', index: '41'),
  GameContents(name: '연어', index: '42'),
  GameContents(name: '다이빙', index: '43'),
  GameContents(name: '고구려', index: '44'),
  GameContents(name: '선생님', index: '45'),
  GameContents(name: '경전철', index: '46'),
  GameContents(name: '물회', index: '47'),
  GameContents(name: '디자이너', index: '48'),
  GameContents(name: '미역', index: '49'),
  GameContents(name: '북극곰', index: '50'),
];

final List<GameContents> music1990 = [
  GameContents(name: 'ㄴㅂ', answer: '나비', index: '1'),
  GameContents(name: 'ㅅㄹㅇㅇ', answer: '사랑해요', index: '2'),
  GameContents(name: 'ㅅㄹㅇ ㅇㅅㅇ ㅇㅇㄷㅁ', answer: '사랑에 연습이 있었다면', index: '3'),
  GameContents(name: 'ㄴ ㅇㄹㅇ', answer: '난 알아요', index: '4'),
  GameContents(name: 'ㄱ ㅈㅇ ㄱㄷㄹ ㅁㄴ', answer: '그 중에 그대를 만나', index: '5'),
  GameContents(name: 'ㅎㅂㄹㄱ', answer: '해바라기', index: '6'),
  GameContents(name: 'ㅈㅁㄷ ㅁㄴ', answer: '잘못된 만남', index: '7'),
  GameContents(name: 'ㄱㄹ ㅅㄹㅁ ㄸ ㅇㅅㅂㄴㅅ', answer: '그런 사람 또 없습니다', index: '8'),
  GameContents(name: 'ㅁㄹㅅㄱ', answer: '모래시계', index: '9'),
  GameContents(name: 'ㅇㅇㄴ', answer: '잊었니', index: '10'),
  GameContents(name: 'ㄴㅈ ㅁㅎㅊㄹ', answer: '남자 만화처럼', index: '11'),
  GameContents(name: 'ㄴㄹ ㅍㅇ ㅇㅇㅁ', answer: '너를 품에 안으면', index: '12'),
  GameContents(name: 'ㄴㅇㄱㄹ ㄸ ㄱㄱ ㅅㅇ', answer: '너에게로 또 가고 싶어', index: '13'),
  GameContents(name: 'ㅂㄲ ㅇㄷ', answer: '벚꽃 엔딩', index: '14'),
  GameContents(name: 'ㄴ ㅇㅇㅇ ㄱㅂㅇ', answer: '내 이름은 권보아', index: '15'),
  GameContents(name: 'ㄷ ㅅ ㅁㅇ', answer: '두 손 모아', index: '16'),
  GameContents(name: 'ㅇㄹ ㅇㅂㅇㅎㄷ ㅈㄱㅈ', answer: '우리 이별했던 정거장', index: '17'),
  GameContents(name: 'ㅅㄹㅇㅃㅇ', answer: '사랑일뿐야', index: '18'),
  GameContents(name: 'ㄴㅇㄱㄹ ㄸ ㄱㄱ ㅅㅇ', answer: '너에게로 또 가고 싶어', index: '19'),
  GameContents(name: 'ㄴㅁㅇ', answer: '너만이', index: '20'),
  GameContents(name: 'ㅊㅎ', answer: '청혼', index: '21'),
  GameContents(name: 'ㅇㅈㅊㄹ', answer: '어제처럼', index: '22'),
  GameContents(name: 'ㅎㅎㅎㅅ', answer: '하하하쏭', index: '23'),
  GameContents(name: 'ㅂㅅ', answer: '비상', index: '24'),
  GameContents(name: 'ㄱㅇ ㅅㅇ ㅁㅅ', answer: '기억 속의 미소', index: '25'),
  GameContents(name: 'ㅇㅂㅈ', answer: '아버지', index: '26'),
  GameContents(name: 'ㅊㅇ ㄱ ㄴㄲㅊㄹ', answer: '처음 그 느낌처럼', index: '27'),
  GameContents(name: 'ㅇㅇㅇ ㅎㄷㄴ ㅁㅇㅇㄹ', answer: '잊어야 한다는 마음으로', index: '28'),
  GameContents(name: 'ㅇㅅㅎ ㅇㅎ', answer: '이상한 여행', index: '29'),
  GameContents(name: 'ㅎㅇ', answer: '희야', index: '30'),
  GameContents(name: 'ㅇㅂㅇ ㅈㄴㅁ', answer: '이밤이 지나면', index: '31'),
  GameContents(name: 'ㅂㄱㅂㄱ', answer: '빙글빙글', index: '32'),
  GameContents(name: 'ㅂㄹㅇ ㅂㅇㅇㅁ ㅈㄱㅇ', answer: '바람이 불었으면 좋겠어', index: '33'),
  GameContents(name: 'ㅁㄴ ㅋㅍ', answer: '모닝 커피', index: '34'),
  GameContents(name: 'ㄱㅅ ㅇㄷㅇ', answer: '교실 이데아', index: '35'),
  GameContents(name: 'ㅇㄸㄱㅇ', answer: '어떤가요', index: '36'),
  GameContents(name: 'ㅂㄹㅇ ㄴㄹ', answer: '바람의 노래', index: '37'),
  GameContents(name: 'ㄴ ㅇㄹㅈ ㄲ', answer: '나 어릴적 꿈', index: '38'),
  GameContents(name: 'ㅇㄷㅇ', answer: '안돼요', index: '39'),
  GameContents(name: 'ㅈㄴ', answer: '자니', index: '40'),
  GameContents(name: 'ㅇㄸㄱ ㅅㄹㅇ ㄱㄹㅇ ㄱㄹㅇ', answer: '어떻게 사랑이 그래요', index: '41'),
  GameContents(name: 'ㅇㅂ ㄱㄹㄱ ㅁㄹ', answer: '이별 그리고 미련', index: '42'),
  GameContents(name: 'ㅁㅂㅇ ㅊㅊ', answer: '맨발의 청춘', index: '43'),
  GameContents(name: 'ㄱ ㄴㅈ ㄱ ㅇㅈ', answer: '그 남자 그 여자', index: '44'),
  GameContents(name: 'ㅂㄹㄱㅇ ㅅㅇ', answer: '바람결에 실어', index: '45'),
  GameContents(name: 'ㅅㄹㅎㅈㅁ', answer: '사랑했지만', index: '46'),
  GameContents(name: 'ㄴㄴ ㅇㄹㅇ', answer: '나는 외로워', index: '47'),
  GameContents(name: 'ㄷㅈ', answer: '답장', index: '48'),
  GameContents(name: 'ㅁㅎㅈ ㅁ', answer: '말하지 마', index: '49'),
  GameContents(name: 'ㅅㄹㅎ ㅎㅇ', answer: '사랑한 후에', index: '50'),
];

final List<GameContents> music2000 = [
  GameContents(name: 'ㅈㅈ', answer: '점점', index: '1'),
  GameContents(name: 'ㄴㅇ ㄲ', answer: '눈의 꽃', index: '2'),
  GameContents(name: 'ㅅㄹㅎㄴㅂ', answer: '사랑했나봐', index: '3'),
  GameContents(name: 'ㅁㅈㅁ ㅇㅅ', answer: '마지막 인사', index: '4'),
  GameContents(name: 'ㅎㄹ ㅎㄹ', answer: '하루 하루', index: '5'),
  GameContents(name: 'ㅅㄹ ㅇㅇ', answer: '사랑 앓이', index: '6'),
  GameContents(name: 'ㅊㄱㅇ', answer: '친구여', index: '7'),
  GameContents(name: 'ㄱㅅ', answer: '감사', index: '8'),
  GameContents(name: 'ㅎㅈㅅ ㅇㄴ ㅇ', answer: '해줄 수 없는 일', index: '9'),
  GameContents(name: 'ㄱㅈㅁ', answer: '거짓말', index: '10'),
  GameContents(name: 'ㅊㅁㅇㄱㅊㄹ', answer: '총맞은것처럼', index: '11'),
  GameContents(name: 'ㄴ ㄴㄹ ㅅㄹㅎ', answer: '난 너를 사랑해', index: '12'),
  GameContents(name: 'ㄱㄷㄱ ㅂㄷ', answer: '그대가 분다', index: '13'),
  GameContents(name: 'ㄴㅅㄹ', answer: '내사람', index: '14'),
  GameContents(name: 'ㅅㅋㅅ', answer: '서커스', index: '15'),
  GameContents(name: 'ㄴㄱ ㅇㄴㄱ ㅇㄴㅇ', answer: '내가 웃는 게 아니야', index: '16'),
  GameContents(name: 'ㅌㅁ', answer: '텔미', index: '17'),
  GameContents(name: 'ㅅㅇㅇ ㅁㅎㅂ', answer: '소원을 말해봐', index: '18'),
  GameContents(name: 'ㅂㅆ ㅇㄴ', answer: '벌써 일년', index: '19'),
  GameContents(name: 'ㄷㅅ ㅅㄹㅎㄷ ㅁㅎㄲ', answer: '다시 사랑한다 말할까', index: '20'),
  GameContents(name: 'ㄴㄱ ㅇㄴ ㄱ', answer: '내게 오는 길', index: '21'),
  GameContents(name: 'ㅇㄹㅎ', answer: '아로하', index: '22'),
  GameContents(name: 'ㄴㅁㄱㅇㅇ', answer: '낭만고양이', index: '23'),
  GameContents(name: 'ㅂㅁ', answer: '비몽', index: '24'),
  GameContents(name: 'ㅇㅌㄹㅌㅅ ㅅㄴ', answer: '아틀란티스 소녀', index: '25'),
  GameContents(name: 'ㅊㄴ', answer: '체념', index: '26'),
  GameContents(name: 'ㄱㅎㅁ ㅇㄱ', answer: '광화문 연가', index: '27'),
  GameContents(name: 'ㅂㅊㅂ', answer: '불치병', index: '28'),
  GameContents(name: 'ㅈㅇ ㅅㄹ', answer: '좋은 사람', index: '29'),
  GameContents(name: 'ㄱㅅ', answer: '가시', index: '30'),
  GameContents(name: 'ㄴㅇㄱㄹ ㄸㄴㄴ ㅇㅎ', answer: '나에게로 떠나는 여행', index: '31'),
  GameContents(name: 'ㅅㄹㅅㄹㅇ', answer: '사랑스러워', index: '32'),
  GameContents(name: 'ㅌㅇㅇ ㅍㅎㄴ ㅂㅂ', answer: '태양을 피하는 방법', index: '33'),
  GameContents(name: 'ㅈㄴ', answer: '자니', index: '34'),
  GameContents(name: 'ㅁㅇㅇ', answer: ' 만약에', index: '35'),
  GameContents(name: 'ㅅㄹ ㅇㅎ', answer: '사랑 안해', index: '36'),
  GameContents(name: 'ㄴㅈㄹ ㅁㄹ', answer: '남자를 몰라', index: '37'),
  GameContents(name: 'ㄱㄹㅇㅅ', answer: '거리에서', index: '38'),
  GameContents(name: 'ㅂㅎㄱ', answer: '비행기', index: '39'),
  GameContents(name: 'ㅈㅅㄹ', answer: '잔소리', index: '40'),
  GameContents(name: 'ㅊㅇㅇ ㅅㄹㅇ ㄷㅇ', answer: '추억은 사랑을 닮아', index: '41'),
  GameContents(name: 'ㅈㅇ ㄴ', answer: '죽일 놈', index: '42'),
  GameContents(name: 'ㄲㅇ', answer: '꿈에', index: '43'),
  GameContents(name: 'ㅎㅈㅇ ㄱㅊㄱ', answer: '화장을 고치고', index: '44'),
  GameContents(name: 'ㄱㅇ ㅂㄱ', answer: '같은 베개', index: '45'),
  GameContents(name: 'ㅅㄱㅈ', answer: '세글자', index: '46'),
  GameContents(name: 'ㄹㄷㄷ', answer: '링딩동', index: '47'),
  GameContents(name: 'ㅇㅂㄹㅋㅌㅂㄹ', answer: '아브라카타브라', index: '48'),
  GameContents(name: 'ㅎㅇㅅ', answer: '핫이슈', index: '49'),
  GameContents(name: 'ㄴㅂㄷ', answer: '노바디', index: '50'),
];

final List<GameContents> music2010 = [
  GameContents(name: 'ㅈㅅㄹ', answer: '잔소리', index: '1'),
  GameContents(name: 'ㅈㅇㄷ ㅁ ㅂㄴ', answer: '죽어도 못 보내', index: '2'),
  GameContents(name: 'ㄴ ㄸㅁㅇ ㅁㅊ', answer: '너 때문에 미쳐', index: '3'),
  GameContents(name: 'ㅂㅁ ㅈ ㅁㄷㄹ', answer: '밥만 잘 먹더라', index: '4'),
  GameContents(name: 'ㄹㅍ', answer: '루팡', index: '5'),
  GameContents(name: 'ㅇㅌㅇㅇ', answer: '외톨이야', index: '6'),
  GameContents(name: 'ㄱㅂ', answer: '고백', index: '7'),
  GameContents(name: 'ㄴ ㅂㅈㅇ ㄴㄹ', answer: '널 붙잡을 노래', index: '8'),
  GameContents(name: 'ㄹㄹㅍㄹ', answer: '롤리폴리', index: '9'),
  GameContents(name: 'ㄴㄱ ㅈㅇ ㅈ ㄴㄱ', answer: '내가 제일 잘 나가', index: '10'),
  GameContents(name: 'ㅂㄱ ㅇㄴ ㄴㅇ', answer: '비가 오는 날엔', index: '11'),
  GameContents(name: 'ㅈㅇㄴ', answer: '좋은 날', index: '12'),
  GameContents(name: 'ㅇㄴㅇㄹㄱ ㅁㅎㅈㅁ', answer: '안녕이라고 말하지마', index: '13'),
  GameContents(name: 'ㅂㅂㄷㅊ', answer: '별빛달빛', index: '14'),
  GameContents(name: 'ㅅㅇㅂㅇ', answer: '샤이보이', index: '15'),
  GameContents(name: 'ㄱㄴㅅㅌㅇ', answer: '강남스타일', index: '16'),
  GameContents(name: 'ㄴㅎㅈ', answer: '나혼자', index: '17'),
  GameContents(name: 'ㅎㄹ ㄲ', answer: '하루 끝', index: '18'),
  GameContents(name: 'ㅊㅅㄹ', answer: '첫사랑', index: '19'),
  GameContents(name: 'ㄴㄹ ㅅㄹㅎㄷ ㅅㄹㅇ', answer: '나를 사랑했던 사람아', index: '20'),
  GameContents(name: 'ㅇㅈㅈㅁ ㅈㅂ', answer: '이러지마 제발', index: '21'),
  GameContents(name: 'ㄴㄹ ㄴ', answer: '너랑 나', index: '22'),
  GameContents(name: 'ㅂㅇㅈㄱ', answer: '보여줄게', index: '23'),
  GameContents(name: 'ㅇㄹㅁ ㅁㅇㅇ', answer: '이름이 뭐예요', index: '24'),
  GameContents(name: 'ㅂㄲ ㅇㄷ', answer: '벚꽃 엔딩', index: '25'),
  GameContents(name: 'ㅊ ㅅㄹㄴ', answer: '첫 사랑니', index: '26'),
  GameContents(name: 'ㅇㅅㅎ', answer: '야생화', index: '27'),
  GameContents(name: 'ㄱㅇㅇㅇ ㅁㄴㅇ', answer: '금요일에 만나요', index: '28'),
  GameContents(name: 'ㅇㅅㅎ', answer: '그 중에 그대를 만나', index: '29'),
  GameContents(name: 'ㅎㅇㄹㅂㅇ ㄲ', answer: '한여름밤의 꿀', index: '30'),
  GameContents(name: 'ㄴㄹㄱ ㄴㅇㅇ', answer: '노래가 늘었어', index: '31'),
  GameContents(name: 'ㄲㅌㄹㄴ', answer: '까탈레나', index: '32'),
  GameContents(name: 'ㅇㄹㄱㅁ ㄱㄹㅈㅁㅈ', answer: '이럴거면 그러지말지', index: '33'),
  GameContents(name: 'ㄲㄴ ㅁㅇㅇ', answer: '꺼내 먹어요', index: '34'),
  GameContents(name: 'ㅇㅇㅎ ㅂ', answer: '우연히 봄', index: '35'),
  GameContents(name: 'ㄷㄹ ㄴㅈ ㅁㄱ ㄴ', answer: '다른 남자 말고 너', index: '36'),
  GameContents(name: 'ㄷㅅㄹ', answer: '두사랑', index: '37'),
  GameContents(name: 'ㅇㅇㅇㅇ', answer: '음오아예', index: '38'),
  GameContents(name: 'ㅇㄴㅂㅌ ㅇㄹㄴ', answer: '오늘부터 우리는', index: '39'),
  GameContents(name: 'ㄱㅎㅁㅇㅅ', answer: '광화문에서', index: '40'),
  GameContents(name: 'ㅅㄱㅇ ㄷㄹㅅ', answer: '시간을 달려서', index: '41'),
  GameContents(name: 'ㄴㄱ ㅈㅈㄹ ㅅㄹ', answer: '내가 저지른 사랑', index: '42'),
  GameContents(name: 'ㅂㄴ', answer: '봄날', index: '43'),
  GameContents(name: 'ㄴ ㄴㅁ ㅁㄹㄱ', answer: '널 너무 모르고', index: '44'),
  GameContents(name: 'ㄱㄷㄹㄴ ㅅㅊ', answer: '그대라는 사치', index: '45'),
  GameContents(name: 'ㅁㄷㄴ ㅁㄷ ㅅㄱ', answer: '모든 날 모든 순간', index: '46'),
  GameContents(name: 'ㅂㅇ ㅂㄴㄴ ㅂ', answer: '별이 빛나는 밤', index: '47'),
  GameContents(name: 'ㅈㅇ ㄱㄷㅇ ㅇㅎ ㅅ', answer: '작은 것들을 위한 시', index: '48'),
  GameContents(name: 'ㄴㄹ ㅁㄴ', answer: '너를 만나', index: '49'),
  GameContents(name: 'ㅈㅈㅎㄴ ㅇㅇㄷㅇ ㅇㅎ', answer: '주저하는 연인들을 위해', index: '50'),
];
final List<GameContents> music2020 = [
  GameContents(name: 'ㅇㅁㄴㄹ', answer: '아무노래', index: '1'),
  GameContents(name: 'ㅇㄹㅎ', answer: '아로하', index: '2'),
  GameContents(name: 'ㅇㅇ', answer: '에잇', index: '3'),
  GameContents(name: 'ㅅㅈ', answer: '시작', index: '4'),
  GameContents(name: 'ㅁㅇㅇ ㄷㄹㅇ', answer: '마음을 드려요', index: '5'),
  GameContents(name: 'ㅊㅇㅊㄹ', answer: '처음처럼', index: '6'),
  GameContents(name: 'ㅅㅉ ㅅㄹㅇ', answer: '살짝 설렜어', index: '7'),
  GameContents(name: 'ㄷㅅ ㅇㄱ ㅂㄷㄱ', answer: '다시 여기 바닷가', index: '8'),
  GameContents(name: 'ㅅㄹㅎㄱ ㄷ ㅈ ㅇㅇㅇ', answer: '사랑하게 될 줄 알았어', index: '9'),
  GameContents(name: 'ㄴㄹ ㅅㄹㅎㄱ ㅇㅇ', answer: '너를 사랑하고 있어', index: '10'),
  GameContents(name: 'ㄴㄴㄴㄴ', answer: '눈누난나', index: '11'),
  GameContents(name: 'ㅅㄷ ㄲㅇ ㅁㅇ ㅈㄷ', answer: '시든 꽃에 물을 주듯', index: '12'),
  GameContents(name: 'ㅎㄹㅎㅈ ㅇㅇ ㄱㅂ', answer: '화려하지 않은 고백', index: '13'),
  GameContents(name: 'ㅍㅈㅁㅊ', answer: '포장마차', index: '14'),
  GameContents(name: 'ㅅㄹㅇ ㅇㅅㅇ ㅇㅇㄷㅁ', answer: '사랑에 연습이 있었다면', index: '15'),
  GameContents(name: 'ㄱㄷ ㄱㅇ ㄴㅅㄹ', answer: '그대 고운 내사랑', index: '16'),
  GameContents(name: 'ㅅㅊ', answer: '시차', index: '17'),
  GameContents(name: 'ㄷㄷㄷㄷ', answer: '덤디덤디', index: '18'),
  GameContents(name: 'ㄱㄷㄹㄴ ㅅ', answer: '그대라는 시', index: '19'),
  GameContents(name: 'ㄹㄹ', answer: '롤린', index: '20'),
  GameContents(name: 'ㄹㅇㄹ', answer: '라일락', index: '21'),
  GameContents(name: 'ㅅㅎㄷ', answer: '신호등', index: '22'),
  GameContents(name: 'ㅂㅎㄴㅇ ㅂㅇ', answer: '밤하늘의 별을', index: '23'),
  GameContents(name: 'ㅇㄹㄷ ㄴㄹ', answer: '오래된 노래', index: '24'),
  GameContents(name: 'ㅊㅁㅂㄹ', answer: '치맛바람', index: '25'),
  GameContents(name: 'ㅇㅇㅇ ㄴㅇ ㅂㄷ', answer: '아이와 나의 바다', index: '26'),
  GameContents(name: 'ㅁㄹㅇ', answer: '마리아', index: '27'),
  GameContents(name: 'ㅂㄹㅁ ㅂㄷ', answer: '바라만 본다', index: '28'),
  GameContents(name: 'ㅈㅇ ㅇㅈ ㅇㄴㅇ', answer: '잠이 오질 않네요', index: '29'),
  GameContents(name: 'ㅅㄹㅇㄱ ㅂ', answer: '사랑인가 봐', index: '30'),
  GameContents(name: 'ㅅㄹㅇ ㄴ ㄷㅁㄱ', answer: '사랑은 늘 도망가', index: '31'),
  GameContents(name: 'ㅊㅈㄱㅂ', answer: '취중고백', index: '32'),
  GameContents(name: 'ㅂㅇㄹㄱㅇㄱㅇ', answer: '봄여름가을겨울', index: '33'),
  GameContents(name: 'ㅈㅇㄹㄱ ㅎㅈ', answer: '정이라고 하자', index: '34'),
  GameContents(name: 'ㅎㅈㅁㅁ', answer: '회전목마', index: '35'),
  GameContents(name: 'ㄷㄹㅁ', answer: '드라마', index: '36'),
  GameContents(name: 'ㄴㅇ ㅁㄷ ㅅㄱ', answer: '너의 모든 순간', index: '37'),
  GameContents(name: 'ㅅㅃ', answer: '새삥', index: '38'),
  GameContents(name: 'ㄴㅇ ㅇㅈㅇ', answer: '눈이 오잖아', index: '39'),
  GameContents(name: 'ㅅㄱㅇ ㅈㅍㅅ', answer: '사건의 지평선', index: '40'),
  GameContents(name: 'ㄱㅂ', answer: '고백', index: '41'),
  GameContents(name: 'ㄴㅎ', answer: '낙하', index: '42'),
  GameContents(name: 'ㅇㄴㄷ ㅂㄴㄴ ㄴㅇㄱ', answer: '오늘도 빛나는 너에게', index: '43'),
  GameContents(name: 'ㅊㄱㄹ  ㅂㄹ', answer: '취기를 빌려', index: '44'),
  GameContents(name: 'ㅎㄹㅇㅇ ㄲ', answer: '후라이의 꿈', index: '45'),
  GameContents(name: 'ㅎㅇㅈㅈ ㅁㅎㅇ', answer: '헤어지자 말해요', index: '46'),
  GameContents(name: 'ㅅㅁㅇㅅ ㄲㅇ ㅍㅇㄷ', answer: '사막에서 꽃을 피우듯', index: '47'),
  GameContents(name: 'ㅋㅋ', answer: '퀸카', index: '48'),
  GameContents(name: 'ㅈ ㅈㄴㅈ ㅇㄹ', answer: '잘 지내자 우리', index: '49'),
  GameContents(name: 'ㅍㅇㅌ ㅎㅇㅈ', answer: '파이팅 해야지', index: '50'),
];

final List<GameContents> movie = [
  GameContents(name: 'assets/movie/오징어게임.png', answer: '우린 깐부잖아', index: '1'),
  GameContents(
      name: 'assets/movie/해바라기.png',
      answer: '꼭 그렇게⋯ 다 가져가야만⋯\n속이 후련했냐!',
      index: '2'),
  GameContents(name: 'assets/movie/곡성.png', answer: '뭣이 중헌디!', index: '3'),
  GameContents(
      name: 'assets/movie/박하사탕.png', answer: '나 다시 돌아갈래~ ', index: '4'),
  GameContents(
      name: 'assets/movie/극한직업.png',
      answer: '지금까지 이런 맛은 없었다.\n이것은 갈비인가 통닭인가',
      index: '5'),
  GameContents(name: 'assets/movie/타짜.png', answer: '묻고 더블로 가!', index: '6'),
  GameContents(
      name: 'assets/movie/지붕뚫고 하이킥.png', answer: '이 빵꾸똥꾸야!', index: '7'),
  GameContents(
      name: 'assets/movie/아저씨.png', answer: '이거 방탄유리야\n이 개**야!', index: '8'),
  GameContents(
      name: 'assets/movie/내부자들.png',
      answer: '모히또 가가지고\n몰디브나 한 잔 할라니까',
      index: '9'),
  GameContents(
      name: 'assets/movie/도깨비.png',
      answer: '날이 좋아서, 날이 좋지 않아서,\n날이 적당해서 모든 날이 좋았다',
      index: '10'),
  GameContents(name: 'assets/movie/타짜2.png', answer: '쏠 수 있어!', index: '11'),
  GameContents(name: 'assets/movie/최고의 사랑.png', answer: '극 뽁 ~', index: '12'),
  GameContents(
      name: 'assets/movie/어게인 마이 라이프.png',
      answer: '진행시켜.',
      index: '13'),
  GameContents(name: 'assets/movie/야인시대.png', answer: '4딸라', index: '14'),
  GameContents(
      name: 'assets/movie/기생충.png', answer: '너는 다 계획이 있구나', index: '15'),
  GameContents(
      name: 'assets/movie/친구.png', answer: '느그 아부지 머하시노.', index: '16'),
  GameContents(
      name: 'assets/movie/사랑했나봐.png',
      answer: '예나…선정이 딸이에요',
      index: '17'),
  GameContents(
      name: 'assets/movie/타짜3.png',
      answer: '예림이! 그 패 봐봐, 혹시 장이야?',
      index: '18'),
  GameContents(
      name: 'assets/movie/상속자들.png', answer: '나, 너 좋아하냐?', index: '19'),
  GameContents(
      name: 'assets/movie/부당거래.png',
      answer: '호의가 계속되면,\n그게 권리인 줄 알아요',
      index: '20'),
  GameContents(name: 'assets/movie/아이리스.png', answer: '아악 안돼', index: '21'),
  GameContents(
      name: 'assets/movie/천국의 계단.png', answer: '사랑은, 돌아오는 거야 ~ !', index: '22'),
  GameContents(
      name: 'assets/movie/파리의 연인.png', answer: '이 안에 너 있다', index: '23'),
  GameContents(
      name: 'assets/movie/내 머리속의 지우개.png',
      answer: '이거 마시면 나랑 사귀는 거다',
      index: '24'),
  GameContents(name: 'assets/movie/올드보이.png', answer: '누구냐, 넌', index: '25'),
  GameContents(
      name: 'assets/movie/친절한 금자씨.png', answer: '너나 잘하세요', index: '26'),
  GameContents(
      name: 'assets/movie/스카이캐슬.png', answer: '전적으로 저를\n믿으셔야 합니다', index: '27'),
  GameContents(name: 'assets/movie/더글로리.png', answer: '멋지다 연진아~', index: '28'),
  GameContents(
      name: 'assets/movie/살인의 추억.png', answer: '밥은 먹고 다니냐?', index: '29'),
  GameContents(
      name: 'assets/movie/범죄도시.png', answer: '어, 아직 싱글이야', index: '30'),
  GameContents(
      name: 'assets/movie/태조 왕건.png',
      answer: '누구인가? 누가 기침소리를 내었는가?',
      index: '31'),
  GameContents(
      name: 'assets/movie/어벤져스(인피니티 워).png', answer: '와칸다 포에버', index: '32'),
  GameContents(
      name: 'assets/movie/어벤져스(엔드게임).png',
      answer: 'I am Iron Man',
      index: '33'),
  GameContents(name: 'assets/movie/변호인.png', answer: '국가란 국민입니다!', index: '34'),
  GameContents(
      name: 'assets/movie/겨울왕국1.png',
      answer: 'Do you wanna build a snowman?',
      index: '35'),
  GameContents(
      name: 'assets/movie/킹스맨.png',
      answer: 'Manners, Maketh, Man',
      index: '36'),
  GameContents(
      name: 'assets/movie/무한도전.png', answer: '어데가서 무기받노~', index: '37'),
  GameContents(
      name: 'assets/movie/바람.png', answer: '내 나이?\n서른마흔다섯살이다.', index: '38'),
  GameContents(name: 'assets/movie/범죄도시2.png', answer: '너 납치된거야', index: '39'),
  GameContents(
      name: 'assets/movie/재벌집 막내아들.png', answer: '몇개고? 밥알 말이다', index: '40'),
  GameContents(
      name: 'assets/movie/상속자들2.png',
      answer: '사탄들의 학교에\n루시퍼의 등장이라..',
      index: '41'),
  GameContents(
      name: 'assets/movie/미래를 보는 소년.png',
      answer: '이따 5시에 호떡집에서\n불이 날거에요',
      index: '42'),
  GameContents(
      name: 'assets/movie/쌈마이웨이.png',
      answer: '예쁜 척 하는게 아니라 예쁘게 태어난곤데~',
      index: '43'),
  GameContents(name: 'assets/movie/러브레터.png', answer: '오겡끼데스까~~', index: '44'),
  GameContents(name: 'assets/movie/암살.png', answer: '구멍이 두개지요', index: '45'),
  GameContents(
      name: 'assets/movie/명량.png',
      answer: '신에게는 아직 12척의 배가 남아있사옵니다',
      index: '46'),
  GameContents(name: 'assets/movie/관상.png', answer: '내가 왕이 될 상인가', index: '47'),
  GameContents(
      name: 'assets/movie/7번방의 선물.png', answer: '예승이 콩먹어 콩 비타민 ', index: '48'),
];
